- name: Modify MOTD
  hosts: proxmox
  tasks:
    - name: Change sshd_config to enable PrintMotd
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#PrintMotd'
        line: 'PrintMotd yes'
      notify:
        - Restart SSH daemon
      become: yes
    - name: Set custom MOTD
      copy:
        src: files/motd.txt
        dest: /etc/motd
        mode: '0644'
      become: yes
  handlers:
    - name: Restart SSH daemon
      service:
        name: ssh
        state: restarted
      become: yes